apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: default
spec:
  requirements:
    - key: "topology.kubernetes.io/zone"
      operator: In
      values: [${azs}]
    - key: "karpenter.sh/capacity-type"
      operator: In
      values: ["spot", "on-demand"]
    - key: "node.kubernetes.io/instance-type"              #If not included, all instance types are considered
      operator: In
      values: ["t1.micro", "t2.micro", "t3a.micro", "t3.micro", "t2.small", "t2.medium", "t3.medium"]
  limits:
    resources:
      cpu: 1000
  provider:
    instanceProfile: ${iam-instance-profile-id}
    subnetSelector:
      Name: "${eks-vpc_name}-private*"
    securityGroupSelector:
      karpenter.sh/discovery/${eks-cluster-id}: '${eks-cluster-id}'
  ttlSecondsAfterEmpty: 120
