apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: default
spec:
  requirements:
    - key: "topology.kubernetes.io/zone"
      operator: In
      values: ["eu-west-1b"]                               #Update the correct region and zones
    - key: "karpenter.sh/capacity-type"
      operator: In
      values: ["spot", "on-demand"]
    - key: "node.kubernetes.io/instance-type"              #If not included, all instance types are considered
      operator: In
      values: ["m5.2xlarge", "m5.4xlarge"]
    - key: "kubernetes.io/arch"                            #If not included, all architectures are considered
      operator: In
      values: ["arm64", "amd64"]
  limits:
    resources:
      cpu: 1000
  provider:
    launchTemplate: "karpenter-aws001-preprod-dev-eks"     # Used by Karpenter Nodes
    subnetSelector:
      Name: "${eks-vpc_name}-private*"
    securityGroupSelector:
      kubernetes.io/cluster/aws-dev-spark-eks: owned
  ttlSecondsAfterEmpty: 120
