apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: gpu
spec:
  requirements:
    - key: node.kubernetes.io/instance-type
      operator: In
      values: ["p3.8xlarge", "p3.16xlarge"]
  taints:
    - key: nvidia.com/gpu
      value: true
      effect: “NoSchedule”
  provider:
    instanceProfile: "aws001-preprod-dev-eks-self-managed-ondemand" # self-managed IAM Instance profile Name
  ttlSecondsAfterEmpty: 60
