apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "microservice.fullname" . }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp2
  resources:
    requests:
      storage: 4Gi