spec:
  destination:
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/eldarsagirovda/aws-bb-containerization.git
    targetRevision: main
  ingress:
    host: dev.example.com
