apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: recommendationservice
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: team-eshop
    server: {{ .Values.spec.destination.server }}
  source:
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
    path: apps/helm/recommendationservice
    helm:
      parameters:
        - name: image.tag
          value: "{{ .Values.spec.image.tag }}"
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
