apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: team-eshop
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: team-eshop
    server: { { .Values.spec.destination.server } }
  source:
    repoURL: { { .Values.spec.source.repoURL } }
    targetRevision: { { .Values.spec.source.targetRevision } }
    path: apps/release
    # helm:
    #   parameters:
    #     - name: spec.ingress.host
    #       value: { { .Values.spec.ingress.host } }
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
